"""initial_schema

Revision ID: 10168b82b84c
Revises:
Create Date: 2026-07-03 16:04:25.114987

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10168b82b84c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contactos",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("numero_telefono", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("nombre_contacto", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "estados",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "necesidades",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descripcion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("satisfecha", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ciudades",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("estado_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=127), nullable=False),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hospitales",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ciudad_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["ciudad_id"],
            ["ciudades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "victimas",
        sa.Column("cedula", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("apellidos", sqlmodel.sql.sqltypes.AutoString(length=511), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hospital_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fecha_de_registro", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitales.id"],
        ),
        sa.PrimaryKeyConstraint("cedula"),
    )
    op.create_table(
        "victimas_contactos",
        sa.Column("contacto_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("victima_cedula", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contacto_id"],
            ["contactos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["victima_cedula"],
            ["victimas.cedula"],
        ),
        sa.PrimaryKeyConstraint("contacto_id", "victima_cedula"),
    )
    op.create_table(
        "victimas_necesidades",
        sa.Column("necesidad_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("victima_cedula", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["necesidad_id"],
            ["necesidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["victima_cedula"],
            ["victimas.cedula"],
        ),
        sa.PrimaryKeyConstraint("necesidad_id", "victima_cedula"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("victimas_necesidades")
    op.drop_table("victimas_contactos")
    op.drop_table("victimas")
    op.drop_table("hospitales")
    op.drop_table("ciudades")
    op.drop_table("necesidades")
    op.drop_table("estados")
    op.drop_table("contactos")
    # ### end Alembic commands ###
